<center>ASSIGNMENT 1 - Bhavya Nagpal (VIT)</center>
<style>
    .rendered_html p {
        font-size: 30px;
        text-align:center;
    }
</style>


Question 1

In [5]:
name="Bhavya Nagpal"
age=21
print(name,age)

Bhavya Nagpal 21


-------

Question 2

In [7]:
X="Datascience is used to extract meaningful insights."
print(X.split(" "))

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


------

Question 3

In [8]:
def multiplication(a,b):
    return a*b
result=multiplication(3,5)
print(result)

15


-------

Question 4

In [18]:
States={'Karnataka':'Bengaluru',
        'Maharashtra':'Mumbai',
        'Tamil Nadu':'Chennai',
        'Punjab':'Chandigarh',
        'Rajasthan':'Jaipur'}
print(States.keys())
print(States.values())

dict_keys(['Karnataka', 'Maharashtra', 'Tamil Nadu', 'Punjab', 'Rajasthan'])
dict_values(['Bengaluru', 'Mumbai', 'Chennai', 'Chandigarh', 'Jaipur'])


-------

Question 5

In [14]:
numbers=list(range(1,1001))
print(numbers[::100])

[1, 101, 201, 301, 401, 501, 601, 701, 801, 901]


------

Question 6

In [21]:
import numpy as np
matrix=np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


-------

Question 7

In [26]:
matrix=np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


-------

Question 8

In [28]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[4,3,2],[1,0,-1]])
print(array1+array2)

[[5 5 5]
 [5 5 5]]


-------

Question 9

In [30]:
import pandas as pd
start_date = '2023-02-01'
end_date = '2023-03-01'
date_series = pd.date_range(start=start_date, end=end_date, freq='D')
print(date_series)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


------

Question 10

In [31]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
fr=pd.DataFrame(dictionary)
print(fr)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240


-------

<center>xxxx</center>